services:
  api:
    build:  ./
    volumes:
      - ./api:/api
    environment:
      FLASK_ENV: development
    command: bash -c "flask run --host=0.0.0.0 --port=5000 --debug"
    ports:
      - "5000:5000"
    public: true
    networks:
      - all