services:
  crypto-forecasting-api:
    build:  ./
    volumes:
      - ./crypto-forecasting-api:/crypto-forecasting-api
    environment:
      FLASK_ENV: development
    command: bash -c "flask run --host=0.0.0.0 --port=5000 --debugger"
    ports:
      - "5000:5000"
    public: true
    networks:
      - all